In [1]:
import numpy

In [2]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(11,)

In [6]:
arra2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
type(arra2)

numpy.ndarray

In [8]:
arra2.shape

(3, 4)

In [9]:
arra2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
array1.size

11

In [11]:
arra2.size

12

## numpy array를 만드는 다양한 방법

In [12]:
array1 = numpy.full(6, 7)
print(array1)

[7 7 7 7 7 7]


In [13]:
array1 = numpy.full(6, 0)
array2 = numpy.zeros(6, dtype=int)

In [14]:
print(array1)

[0 0 0 0 0 0]


In [15]:
print(array2)

[0 0 0 0 0 0]


In [16]:
array2 = numpy.ones(6, dtype=int)

In [17]:
print(array2)

[1 1 1 1 1 1]


In [18]:
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)

print(array1)
print()
print(array2)

[0.54322168 0.89634879 0.79245689 0.06696015 0.43235782 0.30125969]

[0.01343146 0.15959577 0.96126463 0.84279984 0.99775183 0.31928495]


In [20]:
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


In [21]:
array1 = numpy.arange(2, 7)
print(array1)

[2 3 4 5 6]


In [22]:
array1 = numpy.arange(3, 17, 3)
print(array1)

[ 3  6  9 12 15]
